config/routes.rb
Rails.application.routes.draw do
  require "admin_constraint"
  mount Ckeditor::Engine => "/ckeditor", constraints: AdminConstraint.new

  #########################################
  #==news url for blog model
  #########################################
    get "/blogs", to: "blogs#index", as: :blogs
    post "blogs", to: "blogs#create"
    get "/blogs/new", to: "blogs#new", as: :new_blog
    get "blogs/:title_for_slug/edit", to: "blogs#edit", as: "edit_blog"
    get "blogs/:title_for_slug", to: "blogs#show", as: "blog"
    patch "blogs/:title_for_slug", to: "blogs#update"
    put "blogs/:title_for_slug", to: "blogs#update"
    delete "blogs/:title_for_slug", to: "blogs#destroy"
  
  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end
  
  root 'home#index'

  match '/about'                      =>        'home#about',                       via: [:get],            :as => 'about'
  match '/college-consulting'         =>        'home#college_consulting',          via: [:get],            :as => 'college_consulting'
  match '/international-students'     =>        'home#international_students',      via: [:get],            :as => 'international_students'
  match '/additional-services'        =>        'home#additional_services',         via: [:get],            :as => 'additional_services'
  match "/contacts"                   =>        "contacts#create",                  via: [:post]
  match "/post_additional_services"   =>        "home#post_additional_services",    via: [:post],            :as => 'post_additional_services'
  match "/post_international_students"   =>        "home#post_international_students",    via: [:post],            :as => 'post_international_students'


  get '/sitemap.xml', to: redirect("https://s3.amazonaws.com/bleventhal/sitemaps/sitemap.xml.gz", status: 301)

end

app/models/blog.rb
class Blog < ApplicationRecord

  validates :title, uniqueness: {case_sensitive: false}

  before_save :title_url_it
  before_save :remove_img

  has_many :images, as: :imageable, :class_name => "Blog::Asset", dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  
  #This is for SEO purposes, you want the url to be the title of the blog instead of its ID
  def title_url_it
    self.title_for_slug = title.downcase.squish.parameterize("-")
  end

  def remove_img
    nokogiri_html_document =  Nokogiri::HTML(self.content) #heroku does not like tmp directory
    nokogiri_html_document.search('img').each do |img|
      img.remove
    end
    self.content_index = nokogiri_html_document
    #note that if you call self.save here, you might run into infinite loops (stack level too deep), even for after_save, after_create and after_update callbacks
  end

end

app/models/blog/asset.rb
class Blog::Asset < Image
  
  ##============================================================##
  ## Paperclip Interpolates
  ##============================================================##
  Paperclip.interpolates :imageable_type do |attachment, style|
    attachment.instance.imageable_type.downcase
  end

  Paperclip.interpolates :imageable_id do |attachment, style|
    attachment.instance.imageable_id
  end

  has_attached_file :pic,
    :path => "#{Rails.env}/:imageable_type/:imageable_id/:style/:filename",
    :styles => { 
      :medium => ["600x300#", :jpg], 
      :large => ["1200x300#", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

  validates_attachment :pic, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @blogs = Blog.order(pubdate: :asc).page(params[:page]).per_page(6)
  end

  def show
  end

  def blog_post
  end

  def new
    @blog = Blog.new
  end
 
  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blog_path(@blog.title_for_slug), notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blog_path(@blog.title_for_slug), notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private

    def set_blog
      @blog = Blog.find_by(title_for_slug: params[:title_for_slug])
    end

    def blog_params
      params.require(:blog).permit(:title, :content, :content_index, :title_for_slug, :video, :video_link, :main_image, :pubdate, :meta_description, :meta_keywords, images_attributes: [:id, :pic, :name, :_destroy])
    end

end

app/views/blogs/_form.html.erb
<%= form_for(blog, :url => (blog.new_record? ? blogs_url : blog_path(blog.title_for_slug)), :html => { :multipart => true }) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.cktext_area :content, class: "form-control ckeditor" %>
  </div>

  <div class="form-group">
    <%= f.label :video %>
    <%= f.check_box :video, class: "form-control ckeditor" %>
  </div>

  <div class="form-group">
    <%= f.label :video_link %>
    <%= f.text_field :video_link, class: "form-control ckeditor" %>
  </div>

  <div class="form-group">
    <%= f.label :meta_description %>
    <%= f.text_field :meta_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :meta_keywords %>
    <%= f.text_field :meta_keywords, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.fields_for :images, @blog.images.build do |t| %>
      <%= t.label :pic, "Main Image" %> <br>

      <% if @blog.images.exists? %>
        <%= image_tag @blog.images[0].pic.url(:medium), id: 'current_image', class: 'mb15' %><br/>
      <% else %>
        <img id="current_image" class="mb5" src="#" alt="">
      <% end %>

      <%= t.file_field :pic, style: "padding: 4px;" %>  
      <%#= In order to make multiple file uploads you'd have to do it like you did in oldpalm, add multiple true, and loop through params[:pic] in your controller and create images that way %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :pubdate %><br>
    <%= f.date_field :pubdate, value: Date.today, class:'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "form-control btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/blog_post.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <hr>
            <img class="img-responsive" src="http://placehold.it/1200x300" alt="">
            <hr>
            <p><i class="fa fa-clock-o"></i> Posted on August 24, 2013 at 9:00 PM</p>
            <hr>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>
            <hr>
        </div>
    </div>
</div>

app/views/blogs/edit.html.erb
<% provide(:title, 'Barbara Leventhal') %>
<% content_for :head do%>
  <!-- <meta name="description" content="home description"> -->
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">

      <h1>Editing Blog</h1>

      <%= render 'form', blog: @blog %>

      <div class="mt15 mb30">
        <%= link_to '< Back', blogs_path, class: 'btn btn-default' %>
        <%= link_to 'Show Blog', blog_path(@blog.title_for_slug), class: 'btn btn-default' %> 
      </div>

    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<% provide(:title, 'Tips From a Pro') %>
<% content_for :head do%>
  <meta name="description" content="Videos, posts, and success stories to help inspire and motivate students.">
  <link rel="canonical" href="<%= request.url %>"/>

  <meta name="author" content="Barbara Leventhal">
  <meta property="article:author" content="https://www.facebook.com/BarbaraKLeventhal/">

  <!-- Twitter Card data --> 
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@barbleventhal">
  <meta name="twitter:title" content="Tips From a Pro">
  <meta name="twitter:description" content="Videos, posts, and success stories to help inspire and motivate students.">
  <meta name="twitter:creator" content="@barbleventhal"> 
  <%# Twitter summary card with large image must be at least 280x150px  %>
  <meta name="twitter:image" content="https://s3.amazonaws.com/bleventhal/hero/blog_hero.jpg">
  <meta name="twitter:image:src" content="https://s3.amazonaws.com/bleventhal/hero/blog_hero.jpg">
  <meta name="twitter:domain" content="<%= request.url %>">


  <!-- Open Graph data --> 
  <meta property="og:locale" content="en" /> 
  <meta property="og:title" content="Tips From a Pro" /> 
  <meta property="og:type" content="article" /> 
  <meta property="og:url" content="<%= request.url %>" /> 
  <meta property="og:image" content="https://s3.amazonaws.com/bleventhal/hero/blog_hero.jpg" /> 
  <meta property="og:description" content="Videos, posts, and success stories to help inspire and motivate students." /> 
  <meta property="og:site_name" content="Barbara Leventhal" /> 
  <meta property="fb:admins" content="1657579320920047" />

  <!-- GOOGLE Structured data -->
  <script type="application/ld+json">
  {
   "@context": "https://schema.org",
   "@type": "Website",
   "publisher": {
     "@type": "Person",
     "name": "Barbara Leventhal",
     "logo": {
       "@type": "ImageObject",
       "url": "https://s3.amazonaws.com/bleventhal/Barbara+Leventhal_Icon_2c_Icon_2c.png",
       "width": 354,
       "height": 354
     }
   },
   "url": "<%= request.url %>",
   "image": {
     "@type": "ImageObject",
     "url": "https://s3.amazonaws.com/bleventhal/hero/blog_hero.jpg"
   },
   "mainEntityOfPage": {
     "@type": "WebPage",
     "@id": "<%= request.url %>"
   },
   "description": "Videos, posts, and success stories to help inspire and motivate students."
  }
  </script>
  <!-- end local meta tags -->
<% end %>

<img src="https://s3.amazonaws.com/bleventhal/hero/blog_hero.jpg" alt="" class="img-responsive center-block">

<div class="container mt30 mb30">

<% if current_user.try(:admin?)%>
  <%= link_to 'New Blog', new_blog_path, class:"btn btn-primary" %>
  <br />
  <br />
<% end %>

    <% @blogs.each do |blog| %>
      <% if blog.video %>
        <div class="row">
          <div class="col-md-5">
            <%= link_to blog.video_link, target: "blank" do %> 
              <div style="position: relative;">
                <%= image_tag(blog.images[0].pic.url(:medium), class:'img-responsive') if blog.images.present?%>
                <img src="https://s3.amazonaws.com/bleventhal/Play-icon.png" class="img-responsive" style="position: absolute; left: 0; top: 0;" alt="">
              </div>
            <% end %>
          </div>

          <div class="col-md-7">
            <h3><%= link_to blog.title, blog.video_link, target: "blank" %></h3>
            <br>
            <p>
              <%= HTML_Truncator.truncate(blog.content_index, 30).html_safe %> <br>
              <%= link_to "Watch Video >", blog.video_link, target: "blank" %>
            </p>
            <% if current_user.try(:admin?) %>
              <%= link_to 'Edit', edit_blog_path(blog.title_for_slug) %>
              <%= link_to 'Destroy', blog_path(blog.title_for_slug), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="row">
          <div class="col-md-5">
              <%= link_to blog_path(blog.title_for_slug) do %> 
                  <%= image_tag(blog.images[0].pic.url(:medium), class:'img-responsive') if blog.images.present?%>
            <% end %>
          </div>

          <div class="col-md-7">
            <h3><%= link_to blog.title, blog_path(blog.title_for_slug) %></h3>
            <br>
            <p><%= HTML_Truncator.truncate(blog.content_index, 30).html_safe %></p>
              <br>
              <%= link_to 'Read More <i class="fa fa-angle-right"></i>'.html_safe, blog_path(blog.title_for_slug) %>
              <%= link_to 'Edit', edit_blog_path(blog.title_for_slug) if current_user.try(:admin?)%>
              <%= link_to 'Destroy', blog_path(blog.title_for_slug), method: :delete, data: { confirm: 'Are you sure?' } if current_user.try(:admin?) %>
          </div>
        </div>
      <% end %>


    <hr>
  <% end %>

      <div class="text-center">
        <%= will_paginate @blogs %>
      </div>
</div>



<%= render 'layouts/fancy_contact_form' %>

app/views/blogs/new.html.erb
<% provide(:title, 'Barbara Leventhal') %>
<% content_for :head do%>
  <!-- <meta name="description" content="home description"> -->
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <h1>New Blog</h1>

      <%= render 'form', blog: @blog %>

      <div class="mt30 mb30">
         <%= link_to 'Back', blogs_path, class: 'btn btn-default' %>
      </div>
     
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<% provide(:title, "#{@blog.title}") %>
<% content_for :head do%>
  <meta name="description" content="<%= @blog.meta_description if @blog.meta_description.present? %>">
  <link rel="canonical" href="<%= request.url %>"/>

  <meta name="author" content="Barbara Leventhal">
  <meta property="article:author" content="https://www.facebook.com/BarbaraKLeventhal/">

  <!-- Twitter Card data --> 
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@barbleventhal">
  <meta name="twitter:title" content="<%= @blog.title %>">
  <meta name="twitter:description" content="<%= @blog.meta_description if @blog.meta_description.present? %>">
  <meta name="twitter:creator" content="@barbleventhal"> 
  <%# Twitter summary card with large image must be at least 280x150px  %>
  <meta name="twitter:image" content="<%= @blog.main_image if @blog.main_image.present? %>">
  <meta name="twitter:image:src" content="<%= @blog.main_image if @blog.main_image.present? %>">
  <meta name="twitter:domain" content="<%= request.url %>">


  <!-- Open Graph data --> 
  <meta property="og:locale" content="en" /> 
  <meta property="og:title" content="<%= @blog.title %>" /> 
  <meta property="og:type" content="article" /> 
  <meta property="og:url" content="<%= request.url %>" /> 
  <meta property="og:image" content="<%= @blog.main_image if @blog.main_image.present? %>" /> 
  <meta property="og:description" content="<%= @blog.meta_description if @blog.meta_description.present? %>" /> 
  <meta property="og:site_name" content="Barbara Leventhal" /> 
  <meta property="fb:admins" content="1657579320920047" />

  <!-- GOOGLE Structured data -->
  <script type="application/ld+json">
  {
   "@context": "https://schema.org",
   "@type": "Website",
   "publisher": {
     "@type": "Person",
     "name": "Barbara Leventhal",
     "logo": {
       "@type": "ImageObject",
       "url": "https://s3.amazonaws.com/bleventhal/Barbara+Leventhal_Icon_2c_Icon_2c.png",
       "width": 354,
       "height": 354
     }
   },
   "url": "<%= request.url %>",
   "image": {
     "@type": "ImageObject",
     "url": "<%= @blog.main_image if @blog.main_image.present? %>"
   },
   "mainEntityOfPage": {
     "@type": "WebPage",
     "@id": "<%= request.url %>"
   },
   "description": "<%= @blog.meta_description if @blog.meta_description.present? %>"
  }
  </script>
  <!-- end local meta tags -->
<% end %>



<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <hr>
      <%= image_tag(@blog.images[0].pic.url(:large), class:'img-responsive') if @blog.images.present? %>
      <hr>
      <p><i class="fa fa-clock-o"></i><%= @blog.pubdate.strftime("%B %d, %Y") if @blog.pubdate.present? %></p>
      <hr>
      <p class="lead"><%= @blog.title %></p>
      <p class="mt30"><%= @blog.content.html_safe %></p>

      <div class="mt30 mb30">
        <%= link_to '< Back', blogs_path %>
        <%= link_to 'Edit', edit_blog_path(@blog.title_for_slug) if current_user.try(:admin?) %>
      </div>
    </div>
  </div>
</div>






<!-- 
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <hr>
            <img class="img-responsive" src="http://placehold.it/1200x300" alt="">
            <hr>
            <p><i class="fa fa-clock-o"></i> Posted on August 24, 2013 at 9:00 PM</p>
            <hr>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>
            <hr>
        </div>
    </div>
</div> -->