config/routes.rb
Rails.application.routes.draw do
  require "admin_constraint"
  mount Ckeditor::Engine => "/ckeditor", constraints: AdminConstraint.new

  #########################################
  #==news url for blog model
  #########################################
    get "/blogs", to: "blogs#index", as: :blogs
    post "blogs", to: "blogs#create"
    get "/blogs/new", to: "blogs#new", as: :new_blog
    get "blogs/:title_for_slug/edit", to: "blogs#edit", as: "edit_blog"
    get "blogs/:title_for_slug", to: "blogs#show", as: "blog"
    patch "blogs/:title_for_slug", to: "blogs#update"
    put "blogs/:title_for_slug", to: "blogs#update"
    delete "blogs/:title_for_slug", to: "blogs#destroy"
  
  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end
  
  root 'home#index'

  match '/about'                      =>        'home#about',                       via: [:get],            :as => 'about'
  match '/college-consulting'         =>        'home#college_consulting',          via: [:get],            :as => 'college_consulting'
  match '/international-students'     =>        'home#international_students',      via: [:get],            :as => 'international_students'
  match '/additional-services'        =>        'home#additional_services',         via: [:get],            :as => 'additional_services'
  match "/contacts"                   =>        "contacts#create",                  via: [:post]
  match "/post_additional_services"   =>        "home#post_additional_services",    via: [:post],            :as => 'post_additional_services'
  match "/post_international_students"   =>        "home#post_international_students",    via: [:post],            :as => 'post_international_students'


  get '/sitemap.xml', to: redirect("https://s3.amazonaws.com/bleventhal/sitemaps/sitemap.xml.gz", status: 301)

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blogs = Blog.last(3)
  end

  def about
  end

  def college_consulting
  end

  def international_students
  end

  def additional_services
  end

  def post_additional_services
    safe_params = params.permit!
    myparams = safe_params.to_h
    @contact = Contact.create(email: params[:additional_services][:email], name: params[:additional_services][:child_name])
    ContactMailer.welcome_email(@contact, myparams).deliver_later
    redirect_to root_path
  end

  def post_international_students
    safe_params = params.permit!
    myparams = safe_params.to_h
    @contact = Contact.create(email: params[:international_students][:email], name: params[:international_students][:child_name])
    ContactMailer.welcome_email(@contact, myparams).deliver_later
    redirect_to root_path
  end

end

app/views/home/about.html.erb
<% provide(:title, 'About Barbara') %>
<% content_for :head do%>
  <meta name="description" content="My mission is to help your child maximize his or her potential by increasing their motivation, and guiding them and their families down the right educational path.">
  <link rel="canonical" href="<%= request.url %>"/>

  <meta name="author" content="Barbara Leventhal">
  <meta property="article:author" content="https://www.facebook.com/BarbaraKLeventhal/">

  <!-- Twitter Card data --> 
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@barbleventhal">
  <meta name="twitter:title" content="About Barbara">
  <meta name="twitter:description" content="My mission is to help your child maximize his or her potential by increasing their motivation, and guiding them and their families down the right educational path.">
  <meta name="twitter:creator" content="@barbleventhal"> 
  <%# Twitter summary card with large image must be at least 280x150px  %>
  <meta name="twitter:image" content="https://s3.amazonaws.com/bleventhal/about/about-header.jpg">
  <meta name="twitter:image:src" content="https://s3.amazonaws.com/bleventhal/about/about-header.jpg">
  <meta name="twitter:domain" content="<%= request.url %>">


  <!-- Open Graph data --> 
  <meta property="og:locale" content="en" /> 
  <meta property="og:title" content="About Barbara" /> 
  <meta property="og:type" content="article" /> 
  <meta property="og:url" content="<%= request.url %>" /> 
  <meta property="og:image" content="https://s3.amazonaws.com/bleventhal/about/about-header.jpg" /> 
  <meta property="og:description" content="My mission is to help your child maximize his or her potential by increasing their motivation, and guiding them and their families down the right educational path." /> 
  <meta property="og:site_name" content="Barbara Leventhal" /> 
  <meta property="fb:admins" content="1657579320920047" />

  <!-- GOOGLE Structured data -->
  <script type="application/ld+json">
  {
   "@context": "https://schema.org",
   "@type": "Website",
   "publisher": {
     "@type": "Person",
     "name": "Barbara Leventhal",
     "logo": {
       "@type": "ImageObject",
       "url": "https://s3.amazonaws.com/bleventhal/Barbara+Leventhal_Icon_2c_Icon_2c.png",
       "width": 354,
       "height": 354
     }
   },
   "url": "<%= request.url %>",
   "image": {
     "@type": "ImageObject",
     "url": "https://s3.amazonaws.com/bleventhal/about/about-header.jpg"
   },
   "mainEntityOfPage": {
     "@type": "WebPage",
     "@id": "<%= request.url %>"
   },
   "description": "My mission is to help your child maximize his or her potential by increasing their motivation, and guiding them and their families down the right educational path."
  }
  </script>
  <!-- end local meta tags -->
<% end %>


<img src="https://s3.amazonaws.com/bleventhal/about/about-header.jpg" alt="" class="img-responsive center-block">

<div class="container mt40 mb40">
  <div class="row">
    <div class="col-md-8 mt20">

      <p>
        Hi, I’m Barbara Leventhal, an educational strategist and founder of Educonsulting in Boca Raton, Florida.   I strive to put college and career planning in the context of the student's life by inspiring middle and high school students to inquire about their possibilities for the future.  I work with students and their families locally, domestically and internationally, giving them the step-by-step guidance needed for submitting standout applications.
        <br>
        <br>
        You can count on me to be at your child’s side every step of the way, in person or through video conference.  I’m here to give your family the advice you need, when you need it.  I want to help your family Plan to Achieve success.
        <br>
        <br>
        As a lifetime educator and mentor with more than 30 years experience, I can help your child stand out from the pool of applicants by showcasing his or her unique story, while providing guidance in making one life’s biggest decisions, which college to attend. Whatever you need, from creating a balanced college list, to help on an essay, to suggestions for meaningful summer classes and community service projects, or a complete comprehensive college plan, I am here to help.
        <br>
        <br>
        <u>Professional Member:</u> Independent Educational Consultants Association(IECA) and the Small Boarding Schools Association(SBSA).
        <br>
        <br>
      </p>
      <div hidden>
        <h3 style="font-weight: 600; font-size:20px;" >PASSION</h3>
        <p>
          I am an educational strategist with more than 30 years of experience in education and mentorship, and I am dedicated to helping your child succeed. As we chart the path to achievement for your child, I draw on my background as a teacher, reading specialist, division director, and director of admissions at various public and independent schools. This experience, paired with frequent visits to colleges and boarding school, has afforded me a high level of expertise that only serves to benefit your child’s educational experience.

        </p>
        <h3 class="mt30" style="font-weight: 600; font-size:20px;">PHILOSOPHY</h3>
        <p>
          I believe that every child’s potential is limitless, and that learning is the key to opening all doors. I have worked with middle and high school students continuously since the day I graduated from college, and have yet to come across a student I did not like. I wake up every day excited to learn what’s new in education and how I can apply that information to my students’ lives.
        </p>
        <h3 class="mt30" style="font-weight: 600; font-size:20px;">PURPOSE</h3>
        <p>
          Every child has a unique set of interests and skills that can be cultivated by empowering him or her to make a correlation to real world experiences. My job is to help students explore who they are, where they are going, and how they will get there. My goal is to put college and career planning in the context of your middle or high school student’s life by inspiring your child to inquire about the possibilities for the future, but most importantly by teaching them to develop plans that facilitate achievement. When my students apply to college, they are able to clearly articulate their passions, talents, contributions to the community, and goals for the future — that is what sets them apart.
        </p>
        <br>
        <a href="#fancy" class="get-contact"> Let's talk ></a><a href="/services" style="margin-left: 30px;">Services Offered ></a>
      </div>
    </div>
    <div class="col-md-4 mt20">
      <img src="https://s3.amazonaws.com/bleventhal/general/mypassion_photo.jpg" class="img-responsive" alt="">
    </div>
  </div>

  <%= render 'layouts/testimonials' %>
  
</div>




<%= render 'layouts/affiliations' %>

app/views/home/additional_services.html.erb
<% provide(:title, 'Additional Educational Services') %>
<% content_for :head do%>
  <meta name="description" content="My goal is to maximize your child’s potential for college admission by focusing not only on school achievement, but also on encouraging personal development.">
  <link rel="canonical" href="<%= request.url %>"/>

  <meta name="author" content="Barbara Leventhal">
  <meta property="article:author" content="https://www.facebook.com/BarbaraKLeventhal/">

  <!-- Twitter Card data --> 
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@barbleventhal">
  <meta name="twitter:title" content="Additional Educational Services">
  <meta name="twitter:description" content="My goal is to maximize your child’s potential for college admission by focusing not only on school achievement, but also on encouraging personal development.">
  <meta name="twitter:creator" content="@barbleventhal"> 
  <%# Twitter summary card with large image must be at least 280x150px  %>
  <meta name="twitter:image" content="http://s3.amazonaws.com/bleventhal/additional-services/additonal-services-header-gradient-w-text.jpg">
  <meta name="twitter:image:src" content="http://s3.amazonaws.com/bleventhal/additional-services/additonal-services-header-gradient-w-text.jpg">
  <meta name="twitter:domain" content="<%= request.url %>">


  <!-- Open Graph data --> 
  <meta property="og:locale" content="en" /> 
  <meta property="og:title" content="Additional Educational Services" /> 
  <meta property="og:type" content="article" /> 
  <meta property="og:url" content="<%= request.url %>" /> 
  <meta property="og:image" content="http://s3.amazonaws.com/bleventhal/additional-services/additonal-services-header-gradient-w-text.jpg" /> 
  <meta property="og:description" content="My goal is to maximize your child’s potential for college admission by focusing not only on school achievement, but also on encouraging personal development." /> 
  <meta property="og:site_name" content="Barbara Leventhal" /> 
  <meta property="fb:admins" content="1657579320920047" />

  <!-- GOOGLE Structured data -->
  <script type="application/ld+json">
  {
   "@context": "https://schema.org",
   "@type": "Website",
   "publisher": {
     "@type": "Person",
     "name": "Barbara Leventhal",
     "logo": {
       "@type": "ImageObject",
       "url": "https://s3.amazonaws.com/bleventhal/Barbara+Leventhal_Icon_2c_Icon_2c.png",
       "width": 354,
       "height": 354
     }
   },
   "url": "<%= request.url %>",
   "image": {
     "@type": "ImageObject",
     "url": "http://s3.amazonaws.com/bleventhal/additional-services/additonal-services-header-gradient-w-text.jpg"
   },
   "mainEntityOfPage": {
     "@type": "WebPage",
     "@id": "<%= request.url %>"
   },
   "description": "My goal is to maximize your child’s potential for college admission by focusing not only on school achievement, but also on encouraging personal development."
  }
  </script>
  <!-- end local meta tags -->
<% end %>

<img src="//s3.amazonaws.com/bleventhal/additional-services/additonal-services-header-gradient-w-text.jpg" alt="" class="img-responsive center-block">

<div class="container mt40 mb40">
  <div class="row">
    <div class="col-sm-12 mt20">
      <p>I maximize your child’s potential not only by focusing on scholastic achievement, but also by emphasizing personal development. Every student has a unique set of interests that can be cultivated by empowering the student to find and follow their passions, build quality relationships and connect lessons to their real world experiences. The curriculum, learning approach, level of nurturing, and educational demands in every school differs; that’s why <span style="font-weight: bold;">finding the right school is so important.</span>
      </p>
    </div>
  </div>
</div>

<section class="bg-orange color-black">
  <div class="container pt30 pb40">
    <div class="row">
      <div class="col-sm-12">
        <h2>Personalized Services Student Checklist</h2>
        <p>Click below to get more information</p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-3 hidden-xs">
        <img src="//s3.amazonaws.com/bleventhal/additional-services/additonal-services-checklist-1.jpg" alt="" class="img-responsive"> <br>
        <img src="//s3.amazonaws.com/bleventhal/additional-services/additonal-services-checklist-2.jpg" alt="" class="img-responsive"> <br>
        <img src="//s3.amazonaws.com/bleventhal/additional-services/additonal-services-checklist-3.jpg" alt="" class="img-responsive">
      </div>
      <div class="col-sm-9">
        <h3>Complete Understanding of Admissions Process</h3>
        <%= form_for :additional_services, url: post_additional_services_path, method: :post do |f| %>
          <%= f.check_box :leadership_development %> <span style="font-weight: 600">Leadership Development:</span> A project helps college-bound students to demonstrate leadership through the development and implementation of unique projects based on their interests. The connection with the real world teaches your child how to channel interests and aptitudes to accomplish a goal that will produce a specific measurable result.<br>

          <%= f.check_box :summer_programs %> <span style="font-weight: 600">Summer Programs:</span> Pre-college programs at boarding schools,colleges and specialty camps help students to explore their interests and develop new skills and talents.<br>

          <%= f.check_box :organizational_skills %> <span style="font-weight: 600">Organization Skills & Study Strategies:</span> Study skills and strategies teach your child how to learn actively and become a more effective and engaged learner.<br>

          <%= f.check_box :subject_tutoring %> <span style="font-weight: 600">Subject Tutoring:</span> Tutors review the work done in the classroom and extend your child’s understanding using methods that match his or her learning style.<br>

          <%= f.check_box :sat_preparation %> <span style="font-weight: 600">ACT, SAT, TOEFL, SSAT Preparation:</span> Diagnostic and prescriptive tutoring and test strategies with elite tutors who prepare your child for success.<br>

          <%= f.check_box :school_consulting %> <span style="font-weight: 600">Boarding School Consulting:</span> Many students thrive with the small classes, personal attention, engaging extracurricular activities, and structured study schedule available in boarding schools.<br>

          <%= f.check_box :school_placement %> <span style="font-weight: 600">Local School Placement:</span> Each school is mission specific and the student-teacher ratio and services vary from school to school. Options include: public, magnet, parochial, and independent day schools.<br>

          <%= f.check_box :gap_programs %> <span style="font-weight: 600">GAP Programs:</span> A break usually taken between high school and college that can include: a PG(post graduation) year at a boarding school, travel, an internship, study abroad, volunteer activities, or research opportunities.<br>
      </div>
    </div>
    <div class="row mt40">
      <div class="col-sm-12 text-center">
        <button href="#" class="btn btn-white" data-toggle="modal" data-target="#addl_services">Submit</button>
      </div>
    </div>

  </div>
</section>

<div id="addl_services" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title mt10 thankyou">Thank you!</h4>
      </div>

      <div class="modal-body">
        <p class="small mb20">This will help me understand how best I can help your child succeed! Please include your child or children's first names and your e-mail address below, and click submit.</p>
          <%= f.label :child_name do %>
            Child's / Children's first name(s)&#42;
          <% end %>
          <%= f.text_field :child_name, class: "form-control", required: true %> 
          <%= f.label :email do %>
            E-Mail&#42;
          <% end %>
          <%= f.text_field :email, class: "form-control", required: true %>
          <div class="text-center pb10">
            <%= f.submit "Submit", class: "btn btn-orange mt30 mb10" %>
          </div>
      </div>

    </div>
  </div>
</div>
<% end %>

 <style>
  .btn-white {
    color: black;
    font-weight: 600;
    background-color: white;
    border-color: white;
    padding: 6px 20px;
  }
  .btn-orange {
    color: black;
    font-weight: 600;
    background-color: #fcaf5d;
    border-color: white;
    padding: 6px 20px;
  }
  .thankyou {
    color: #fcaf5d;
    font-size: 24px;
  }
  .color-black {
    color: black;
  }
 </style>


<%= render 'layouts/affiliations' %>

app/views/home/index.html.erb
<% provide(:title, 'College Consulting and Placement | Barbara Leventhal') %>
<% content_for :head do%>
  <meta name="description" content="With over 30 years of experience as an admissions director and educational consultant, I am passionate about helping my students succeed.">
  <meta name="keywords" content="">
  <link rel="canonical" href="<%= request.url %>"/>

  <meta name="author" content="Barbara Leventhal">
  <meta property="article:author" content="https://www.facebook.com/BarbaraKLeventhal/">

  <!-- Twitter Card data --> 
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@barbleventhal">
  <meta name="twitter:title" content="College Consulting & Placement | Barbara Leventhal">
  <meta name="twitter:description" content="With over 30 years of experience as an admissions director and educational consultant, I am passionate about helping my students succeed.">
  <meta name="twitter:creator" content="@barbleventhal"> 
  <%# Twitter summary card with large image must be at least 280x150px  %>
  <meta name="twitter:image" content="https://s3.amazonaws.com/bleventhal/new-home/Image-3.jpg">
  <meta name="twitter:image:src" content="https://s3.amazonaws.com/bleventhal/new-home/Image-3.jpg">
  <meta name="twitter:domain" content="<%= request.url %>">


  <!-- Open Graph data --> 
  <meta property="og:locale" content="en" /> 
  <meta property="og:title" content="College Consulting & Placement | Barbara Leventhal" /> 
  <meta property="og:type" content="article" /> 
  <meta property="og:url" content="<%= request.url %>" /> 
  <meta property="og:image" content="https://s3.amazonaws.com/bleventhal/new-home/Image-3.jpg" /> 
  <meta property="og:description" content="With over 30 years of experience as an admissions director and educational consultant, I am passionate about helping my students succeed." /> 
  <meta property="og:site_name" content="Barbara Leventhal" /> 
  <meta property="fb:admins" content="1657579320920047" />

  <!-- GOOGLE Structured data -->
  <script type="application/ld+json">
  {
   "@context": "https://schema.org",
   "@type": "Website",
   "publisher": {
     "@type": "Person",
     "name": "Barbara Leventhal",
     "logo": {
       "@type": "ImageObject",
       "url": "https://s3.amazonaws.com/bleventhal/Barbara+Leventhal_Icon_2c_Icon_2c.png",
       "width": 354,
       "height": 354
     }
   },
   "url": "<%= request.url %>",
   "image": {
     "@type": "ImageObject",
     "url": "https://s3.amazonaws.com/bleventhal/new-home/Image-3.jpg"
   },
   "mainEntityOfPage": {
     "@type": "WebPage",
     "@id": "<%= request.url %>"
   },
   "description": "With over 30 years of experience as an admissions director and educational consultant, I am passionate about helping my students succeed."
  }
  </script>
  <!-- end local meta tags -->
<% end %>








  
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class=""></li>
      <li data-target="#myCarousel" data-slide-to="1" class=""></li>
      <li data-target="#myCarousel" data-slide-to="2" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="3" class=""></li>
      <li data-target="#myCarousel" data-slide-to="4" class=""></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="item">
        <img class="first-slide" src="https://s3.amazonaws.com/bleventhal/new-home/Image-1.jpg" alt="First slide" />
        <div class="container">
          <div class="carousel-caption first-car">
            <a href="/additional-services">Additional Services <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
          </div>
        </div>
      </div>
      <div class="item">
        <img class="second-slide" src="https://s3.amazonaws.com/bleventhal/new-home/Image-2.jpg" alt="Second slide">
        <div class="container">
          <div class="carousel-caption second-car">
            <a href="/about#testimonials">See Testimonials <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
          </div>
        </div>
      </div>
      <div class="item active">
        <img class="third-slide" src="https://s3.amazonaws.com/bleventhal/new-home/Image-3.jpg" alt="Third slide">
        <div class="container">
          <div class="carousel-caption third-car">
            <a href="/college-consulting">College Consulting <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
          </div>
        </div>
      </div>
      <div class="item">
        <img class="fourth-slide" src="https://s3.amazonaws.com/bleventhal/new-home/Image-4.jpg" alt="Fourth slide">
        <div class="container">
          <div class="carousel-caption fourth-car">
            <a href="/blogs">Tips From a Pro <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
          </div>
        </div>
      </div>
      <div class="item">
        <img class="fifth-slide" src="https://s3.amazonaws.com/bleventhal/new-home/Image-5.jpg" alt="Fifth slide">
        <div class="container">
          <div class="carousel-caption fifth-car">
            <a href="/international-students">International Students <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
          </div>
        </div>
      </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <i class="fa fa-chevron-left" aria-hidden="true"></i>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <i class="fa fa-chevron-right" aria-hidden="true"></i>
      <span class="sr-only">Next</span>
    </a>
  </div>




  <section class="bg-white mypttop pb35">
      <div class="container-fluid">
        <div class="row pt50">
          <div class="col-md-2 text-center">
            <img src="https://s3.amazonaws.com/bleventhal/new-home/hi-there-Barbara.jpg" alt="" class="img-responsive">
          </div>
          <div class="col-md-9 pr20">
            <h2 class="pb10 color-primary text-left">Hi There!</h2>
            <p class="fts15 lh22">
              As the college admissions process becomes more competitive, maximizing your child’s potential for admittance should be a top priority. My mission is to help them do just that by increasing motivation for personal growth, promoting teamwork between students and families, and providing a wealth of information to guide students and families down the right path.
              <br>
              <br>
              <div class="text-center">
                <a href="#fancy" class="btn btn-custom-primary-border btn-lg get-contact text-center" style="border-color:#d91e3e;">We're Ready!</a>
              </div>
            </p>
          </div>
          <div class="col-md-1"></div>          
        </div>
      </div>
    </div>
  </section>

  <section class="bg-dark-blue tipsfromapro">
    <div class="container-fluid">
      <div class="row pb50">
        <div class="col-md-12 text-left">
          <h2 class="pt25 pb25" style="letter-spacing: 1px; color: white;">Tips From a Pro</h2>
        </div>
          <% @blogs.each do |blog| %>
            <% if blog.video %>
              <div class="col-md-4">
                <%= link_to blog.video_link, target: "blank" do %> 
                  <div style="position: relative;">
                    <%= image_tag(blog.images[0].pic.url(:medium), class:'img-responsive') if blog.images.present?%>
                    <img src="https://s3.amazonaws.com/bleventhal/Play-icon.png" class="img-responsive" style="position: absolute; left: 0; top: 0;" alt="">
                  </div>
                <% end %>
                <br>
                <h3 style="font-weight: 700; color: white;"><%= truncate(blog.title, length: 35) %></h3>
                <div class="ptext">
                  <%= HTML_Truncator.truncate(blog.content_index, 30).html_safe %>
                  <%= link_to 'PLAY VIDEO <i class="fa fa-play" aria-hidden="true"></i>'.html_safe, blog.video_link, target: "blank", style: "color: white; font-weight:600" %>
                </div>
              </div>
            <% else %>
              <div class="col-md-4">
                <%= link_to blog_path(blog.title_for_slug) do %>
                  <%= image_tag(blog.images[0].pic.url(:medium), class:'img-responsive') if blog.images.present?%>
                <% end %>
                <br>
                <h3 style="font-weight: 700; color: white;"><%= truncate(blog.title, length: 35) %></h3>
                <div class="ptext">
                  <%= HTML_Truncator.truncate(blog.content_index, 30).html_safe %> <br>
                  <%= link_to "READ MORE", blog_path(blog.title_for_slug), style: 'color: white;font-weight:600' %>
                </div>
              </div>
            <% end %>
          <% end %>
        <div class="col-md-12 text-center mt20 mb50" hidden>
          <a href="#fancy" class="btn btn-custom-primary-border-grey btn-lg get-contact" style="border-color: #d91e3e;">LET'S PLAN TO ACHIEVE</a>
        </div>
      </div>
    </div>
  </section>

<section class="myapproach bg-white">
  <div class="container-fluid">
    <div class="row pt25">
      <div class="col-md-12 text-center">
      </div>
      <div class="col-md-4 text-center pb20">
        <img src="https://s3.amazonaws.com/bleventhal/home/barbara_students_scaled.jpg" alt="" class="img-responsive">
      </div>
      <div class="col-md-8 pb20">
      <h2 class="pb25 text-left color-primary">My Approach</h2>
        <p class="lh22 fts15">
          With more than 30 years of experience as a reading specialist, middle school director, director of admissions, and educational consultant, I am passionate about helping students find success through learning and exploration.
          <br>
          <br>
          Grades and test scores do not adequately describe the unique qualities of each student. Rather, I believe that the secret to success is to help students discover their unique aptitudes and interests. My approach not only encourages students to identify these strengths and inspirations, but also engages them to harness this power to solve real problems.
          <br>
          <br>
          The result? A true sense of fulfillment gained by "doing" - by creating solutions and contributing value to lives and to the community.
        </p>
      </div>
    </div>
  </div>
</section>


<%= render 'layouts/affiliations' %>