config/routes.rb
Rails.application.routes.draw do
  require "admin_constraint"
  mount Ckeditor::Engine => "/ckeditor", constraints: AdminConstraint.new

  #########################################
  #==news url for blog model
  #########################################
    get "/blogs", to: "blogs#index", as: :blogs
    post "blogs", to: "blogs#create"
    get "/blogs/new", to: "blogs#new", as: :new_blog
    get "blogs/:title_for_slug/edit", to: "blogs#edit", as: "edit_blog"
    get "blogs/:title_for_slug", to: "blogs#show", as: "blog"
    patch "blogs/:title_for_slug", to: "blogs#update"
    put "blogs/:title_for_slug", to: "blogs#update"
    delete "blogs/:title_for_slug", to: "blogs#destroy"
  
  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end
  
  root 'home#index'

  match '/about'                      =>        'home#about',                       via: [:get],            :as => 'about'
  match '/college-consulting'         =>        'home#college_consulting',          via: [:get],            :as => 'college_consulting'
  match '/international-students'     =>        'home#international_students',      via: [:get],            :as => 'international_students'
  match '/additional-services'        =>        'home#additional_services',         via: [:get],            :as => 'additional_services'
  match "/contacts"                   =>        "contacts#create",                  via: [:post]
  match "/post_additional_services"   =>        "home#post_additional_services",    via: [:post],            :as => 'post_additional_services'
  match "/post_international_students"   =>        "home#post_international_students",    via: [:post],            :as => 'post_international_students'


  get '/sitemap.xml', to: redirect("https://s3.amazonaws.com/bleventhal/sitemaps/sitemap.xml.gz", status: 301)

end

app/views/layouts/_affiliations.html.erb
<section class="bg-white pb40">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2 class="pt30 pb5" style="letter-spacing: 0px;">Affiliations & Accreditations</h2>
        <p>I am a member of the Independent Educational Consultants Association, National Association of College Admissions Counselors, and the Small Boarding Schools Association.</p>
      </div>
      <div class="col-md-12 mt30 text-center">
          <img src="https://s3.amazonaws.com/bleventhal/new-home/Home-Page-Affilaitions.jpg" alt="" class="img-responsive" style="margin:0 auto;">
      </div>
    </div>
  </div>
</section>

app/views/layouts/_fancy_contact_form.html.erb
<% unless current_page?("/admin") %>
  <div id="fancy">
    <h2>Plan to achieve... start today.</h2>
    <%= form_for Contact.new, :html => { :id => "new_contact" }, :url => contacts_path, method: "post" do |f| %>
      <div class="left">
        <fieldset class="mail"><%= f.email_field :email, class: "form-control", placeholder: "Email address...", required: true %></fieldset>
        <fieldset class="name"><%= f.text_field :name, class: "form-control", placeholder: "Name...", required: true %></fieldset>
        <fieldset class="subject"><%= f.text_field :phone_number, class: "form-control", placeholder: "Phone number...", required: true %></fieldset>
      </div>
      <div class="right">
        <fieldset class="question"><%= f.text_area :message, class: "form-control", placeholder: "Type here...", required: true %></fieldset>
      </div>
      <div class="btn-holder">
        <%= f.submit "Let's Talk", class: "btn mybutton" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-brown">
  <div class="container pt20 pb40 color-white">
    <div class="row">
      <div class="col-sm-4 text-center mt20">
        <h3>Menu</h3>
        <a href="/about" class="dblh10">About</a>
        <a href="/college-consulting" class="dblh10">College Consulting</a>
        <a href="/blogs" class="dblh10">Tips From a Pro</a>
        <a href="international-students" class="get-contact dblh10">International Students</a> 
        <% if current_user.try(:admin?) %>
          <%= link_to "Sign out", destroy_user_session_path, class: "secondary", :method => :delete %>
        <% end %>
      </div>
      <div class="col-sm-4 text-center smt7 mt20">
        <p class="pt7">
          <a href="https://www.facebook.com/BarbaraKLeventhal/" target="blank"><img src="https://s3.amazonaws.com/bleventhal/new-home/facebook-icon.png" width="50"></a>
          <a href="https://www.instagram.com/barbarakleventhal/" target="blank"><img src="https://s3.amazonaws.com/bleventhal/new-home/Instagram-icon.png" width="50"></a> 
          <a href="https://www.linkedin.com/in/barbara-k-leventhal-017b45a/" target="blank"><img src="https://s3.amazonaws.com/bleventhal/new-home/LinkedIn-icon.png" width="50"></a>
          <a href="https://twitter.com/barbleventhal" target="blank"><img src="https://s3.amazonaws.com/bleventhal/new-home/Twitter-icon.png" width="50"></a>
        </p>
      </div>
      <div class="col-sm-4 text-center smt14 mt20">
        <img src="https://s3.amazonaws.com/bleventhal/Barbara+Leventhal_Logo_TAG_white_scaled.png" alt="" class="img-responsive" style="margin: 0 auto;">
      </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="brand"><img src="//s3.amazonaws.com/bleventhal/Barbara+Leventhal_Icon_2c_Icon_2c.png" alt="" width="100"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="firstli <%= is_active?('/about') %>"><a href="/about">About</a></li>
        <li class="secondli <%= is_active?('/college-consulting') %>"><a href="/college-consulting">College Consulting</a></li>
        <li class="<%= is_active?('/international-students') %>"><a href="/international-students">International Students</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= is_active?('/additional-services') %>"><a href="/additional-services">Additional Services</a></li>
        <li class="<%= is_active?('/blogs') %>"><a href="/blogs">Tips From A Pro</a></li>
        <li><a href="//s3.amazonaws.com/bleventhal/BL-Brochure.pdf" target="blank">Brochure</a></li>
      </ul>
    </div>
  </div>
</nav>





<style>

  #navbar {
    margin-top: 20px;
    margin-left: 0px;
  }
  #navbar .navbar-nav{
    width: 40%;
  }
  #navbar .navbar-nav li{
    width: 33%;
  }
  .firstli {
    margin-right: -20px !important;
  }
  .secondli {
    margin-right: 20px !important;
  }

  .navbar {
      position: relative;
      min-height: 84px;
      margin-bottom: 10px;
      margin-top: 5px;
      background-color: white;
      border: none;
  }
  .brand {
      position: absolute;
      left: 50%;
      margin-left: -50px !important;  /* 50% of your logo width */
      display: block;
      z-index: 99;
  }

  .navbar-default .navbar-nav > li > a {
      color: #777;
      font-size: 14px;
      padding-left: 0;
      padding-right: 0;
      text-align: center;
  }

  .navbar-nav li.current a {
    color: #008bc4;
    text-decoration: underline;
  }
  .navbar-nav li a:hover {
    color: #008bc4!important;
  }

  .navbar-default .navbar-toggle {
    margin-top: 20px;
  }

  .navbar-default .navbar-collapse, .navbar-default .navbar-form {
       border-color: transparent !important; 
  }

  @media only screen and (max-width: 767px) {
    #navbar .navbar-nav {
      margin-top: 30px;
      text-align: right;
      width: 100%;
    }
    #navbar .navbar-nav.navbar-right {
      margin-top: 0px; 
    }
    #navbar .navbar-nav li {
      width: 100%;
      margin-left: auto;
      text-align: right;
    }
    #navbar .navbar-nav li a{
      margin-left: auto;
      text-align: right;
    }
    .firstli {
      margin-right: auto !important;
    }
    .secondli {
      margin-right: auto !important;
    }
  }

</style>





<% if !@blog.present? %>
<div class="halfcircle">
  <img src="https://s3.amazonaws.com/bleventhal/new-home/Circle-Nav-bar.png" alt="" class="center-block">
</div>
<style>
  .halfcircle {
      margin-top: -10px;
      margin-bottom: -45px;
      z-index: 9;
      position: relative;
  }
</style>
<% end %>

app/views/layouts/_new_contact_form.html.erb
<%= form_for Contact.new, :html => { :id => "new_contact" }, :url => {:controller => "contacts", :action => "create"} do |f| %>
  <div class=" control-group">
    <div class="form-group col-xs-12">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Name", required: true, data: {validation_required_message: "Please enter your name."} %>
    </div>
  </div>
  <div class=" control-group">
    <div class="form-group col-xs-12">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control", placeholder: "Email", required: true, data: {validation_required_message: "Please enter your email."} %>
    </div>
  </div>
  <div class=" control-group">
    <div class="form-group col-xs-12">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: "form-control", placeholder: "Phone Number", required: true, data: {validation_required_message: "Please enter your phone number."} %>
    </div>
  </div>
  <div class=" control-group">
    <div class="form-group col-xs-12">
      <%= f.label :message %>
      <%= f.text_area :message, class: "form-control", placeholder: "Message", required: true, rows: 3, data: {validation_required_message: "Please enter your message."} %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="form-group col-xs-12">
      <%= f.submit "Send", class: "btn btn-success btn-lg" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-xs-12">
      <% flash.each do |key, value|  %>
        <p class="alert alert-<%= key %>"><%= value %></p>
      <% end if flash.present?%>
    </div>
  </div>
<% end %>

app/views/layouts/_small_contact_form.html.erb
<div class="popup_form">
  <div class="popup_button"><a><i class="fa fa-comments" aria-hidden="true"></i></a></div>
  <%= form_for Contact.new, :html => { :id => "new_contact" }, :url => contacts_path, method: "post" do |f| %>
    <p>
      <img src="https://s3.amazonaws.com/bleventhal/barbara_chat.png" class="chatimg" width="25" alt="">
      Hi I'm Barbara, how can I help your student plan to achieve?
    </p>
    <%= f.text_area :message, rows: "4", class: "form-control", placeholder: "Type here...", required: true %>
    <div id="chat_form" style="display:none;">
    <p>Please provide the following:</p>
    <%= f.email_field :email, class: "form-control", placeholder: "Email address...", required: true %>
    <%= f.text_field :child_grade_level, class: "form-control", placeholder: "Child's Grade Level...", required: true %>
    <%= f.submit "Let's Talk", class: "btn mybutton form-control" %>
    </div>
  <% end %>
</div>


<style>
.popup_form {
    position:fixed;
    right:8px;
    bottom:3px;
    width:300px;
    font-size:12px;
    z-index: 99;
}
.popup_form .popup_button{
    position:relative;
    right:-14px;
    bottom:0;
    padding:0 0 0 225px;
}
.popup_form .popup_button a{
    padding:0 5px;
    text-align:right;
    background:#D91E3E;
    cursor:pointer;
    font-size: 50px;
}
.popup_button .fa {
  color: white;
}
.popup_form form{
    border:1px solid #666;
    background:#dfdfdf;
    padding:10px;
    display:none;
}
.popup_form form p{
  font-size: 16px;
  color: black;
  margin-top: 7px;
  margin-bottom: 7px;
}
.popup_form .mybutton{
  border-radius: 4px;
  text-align: right;
  margin-top: 7px;
}

.popup_form textarea {
  resize: none;
}
.chatimg {
  margin-bottom: -5px;
}
</style>


<script>
  $(function() {
    $(window).scroll(function() {
      if($(window).scrollTop() + $(window).height() > $(document).height() - ($('footer').height() + 3)) {
        $('.popup_form').css({"position": "fixed", "bottom": ($('footer').height() + 3) - ($(document).height() - ($(window).scrollTop() + $(window).height()))});
      } else {
        $('.popup_form').css({"position": "fixed", "bottom": "3px"});
      }
    });

    $('.popup_form a').on('click',function(){
      $('.popup_form form').slideToggle('slow');
    });
    $('.popup_form textarea').on('keyup',function(e){
      var regex = new RegExp("[A-Za-z]");
      if(e.keyCode == 13 && regex.test($(this).val()))
      {
          $(this).prop('readonly', 'true');
          $('#chat_form').show(1200);
          $('#chat_form #contact_email').focus();
      }
    });
  }());
</script>

app/views/layouts/_test_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user.try(:admin?) %>
        <a class="navbar-brand" href="/">Home</a>
      <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="/about">About</a></li>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/_testimonials.html.erb
<div class="row" id="testimonials">
  <div class="col-md-12 mt50 pt30 pb10" style="background-color: mistyrose;">
    <div class="owl-carousel owl-theme">
      <div class="item text-center">
        <p style="font-size: 20px;"><span style="font-size: 35px;">&#8220;</span>When I first started working with Barbara in high school, I had no idea how I was going to write all the essays for my applications. I felt overwhelmed. It was a detailed process, but Barb kept me on track. She guided my family and me through the many decisions involved in the college admission process, calmed us when we were worried, and made it possible for us to get through the whole process with minimal stress. When it came time to apply to grad school, I went back to Barb again because of how much value she added. Thanks, Barb, I was admitted to all three of my top choice grad schools!<span style="font-size: 35px;">&#8221;</span></p>
        <br>
        <h4 style="font-weight: bold; font-size:24px;">– LAUREN M.</h4>
        <p>Spanish River High School (Class of 2013); Indiana University(Class of 2017)</p>
      </div>
      <div class="item text-center">
        <p style="font-size: 20px;"><span style="font-size: 35px;">&#8220;</span>I was accepted at all of my top schools and was awarded over $200,000 in merit aid, so YES, Barb’s guidance really made a difference.  She gave me actionable feedback that allowed me to improve my essays; we worked together, revising my essays until they were perfect. She managed and respected my workload by scheduling frequent short meetings. I completed all ten of my applications by the early deadline, so I could take advantage of the early admission opportunities and merit aid.<span style="font-size: 35px;">&#8221;</span></p>
        <br>
        <h4 style="font-weight: bold; font-size:24px;">– PARKER D.</h4>
        <p>Scotch Plains/Fanwood High School,NJ (Class of 2017); University of Michigan (Class of 2021)</p>
      </div>
      <div class="item text-center">
        <p style="font-size: 20px;"><span style="font-size: 35px;">&#8220;</span>We know we are not alone in how we feel about you. You are so much more than a coach to your students and their families. Your support and genuine interest in our children’s success and well-being is both touching and invaluable.<span style="font-size: 35px;">&#8221;</span></p>
        <br>
        <h4 style="font-weight: bold; font-size:24px;">– LISA and Wayne W.</h4>
        <p>Parents of Mia W. Saint Andrew’s School(Class of 2013) and SMU (Class of 2017) and Ryan W. (Class of 2016), Saint Andrew’s School</p>
      </div>
      <div class="item text-center">
        <p style="font-size: 20px;"><span style="font-size: 35px;">&#8220;</span>My parents and I were excited and nervous when I traveled from Brazil to the US alone to attend a two-week summer Business Bootcamp at Drexel University in Philadelphia.  My goal was to experience a taste of college in the US before applying.  I got so much more.  I lived in the dorms, made great friends and improved my English. Thank-you Barbara, I loved Drexel and I can’t wait to go to college in the US.<span style="font-size: 35px;">&#8221;</span></p>
        <br>
        <h4 style="font-weight: bold; font-size:24px;">– ARISSA M.</h4>
        <p>Pueri Domus HS, Sao Paolo, Brazil (Class of 2018)</p>
      </div>                        
    </div>
  </div>
</div>

<style>
  .owl-carousel.owl-theme {
    position: relative;
  }

  .owl-theme .owl-nav {
    position: absolute;
    top: 40%;
    margin-top: 0px;
  }

  .owl-nav {
    text-align: center;
    width: 100%;
  }

  .owl-nav .owl-prev {
    position: absolute;
    left: 5px;
  }

  .owl-nav .owl-next {
    position: absolute;
    right: 5px;
  }

  .item.text-center {
    margin: 0 50px;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>


    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title><%= "#{yield(:title)}" if yield(:title).present? %></title>

    <meta name="google-site-verification" content="--OtlRtohJfxuKY9dsonHIlBEelaQG13t2DZe16Esq8" />
    
    <%= favicon_link_tag "//s3.amazonaws.com/bleventhal/Barbara+Leventhal_Icon_2c_Icon_2c.png", rel: "icon", type: "image/png"%>

    <%= yield(:head) %>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', "data-turbolinks-track" => false %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => false %>
  </head>

  <body class='<%= "#{controller_name} #{action_name} #{devise_controller? ? 'devise' : nil}"%>'>
    <% unless current_page?(root_url) %>
      <% flash.each do |key, value| %>
        <% if key == "notice" %>
          <div class="alert alert-success"><%= value %><button class="close" data-dismiss="alert">×</button></div>
        <% elsif key == "alert" %>
          <div class="alert alert-danger"><%= value %><button class="close" data-dismiss="alert">×</button></div>
        <% else %>
          <div class="alert alert-<%= key %>"><%= value %><button class="close" data-dismiss="alert">×</button></div>
        <% end %>
      <% end %>
    <% end %>


    <%= render 'layouts/nav' %>

      <%= yield %>

      <%= render 'layouts/fancy_contact_form' %>
      <%= render 'layouts/small_contact_form' %>
      
    <%= render 'layouts/footer' %>

    <%= "<div style='margin-top:148px;'></div>".html_safe if false && Rails.env.development? %>
    <%= console if false && Rails.env.development? %>
    <script>
      $(function() {

        setTimeout(function() {
          if (!window.name) {
            $(".popup_form a").trigger("click");
            window.name = "1" ;
          }
        }, 5000);

        $('.owl-carousel').owlCarousel({
          loop:true,
          margin:10,
          nav:true,
          navText: ["<i class='fa fa-chevron-left'></i>","<i class='fa fa-chevron-right'></i>"],
          dots: false,
          autoplay: true,
          autoplayTimeout: 30000,
          animateOut: 'fadeOut',
          responsiveClass:true,
          responsive:{
              0:{
                  items:1
              }
          }
        });

        $('.bxslider').bxSlider({
          auto: true,
          pause: 7000,
          speed: 2000
        });
        
        $(".menu-trigger").click(function() {
          $("#menu").fadeToggle(1);
          $(this).toggleClass("active");
          $(".position-txt").toggleClass("toggle-txt");
          $(".position-img").toggleClass("toggle-img");
        });
        
        $('.info-request, .get-contact').fancybox();

      }());


    </script>
  </body>
</html>